-- Script para inicializar productos de la ferretería (Parte 1 - Herramientas)
INSERT OR IGNORE INTO products (code, name, description, category_id, brand, location, active, created_at, updated_at) VALUES
-- HERRAMIENTAS MANUALES - MARTILLOS
('MART-001', 'Martillo de Carpintero', 'Martillo de carpintero con mango de madera', (SELECT id FROM categories WHERE name = 'Martillos'), 'Tramontina', 'A1', 1, datetime('now'), datetime('now')),
('MART-002', 'Martillo de Goma', 'Martillo de goma para trabajo delicado', (SELECT id FROM categories WHERE name = 'Martillos'), 'Stanley', 'A1', 1, datetime('now'), datetime('now')),
('MART-003', 'Martillo de Bola', 'Martillo de bola para mecánica', (SELECT id FROM categories WHERE name = 'Martillos'), 'Facom', 'A1', 1, datetime('now'), datetime('now')),
('MART-004', 'Martillo de Demolición', 'Martillo de demolición pesado', (SELECT id FROM categories WHERE name = 'Martillos'), 'Bosch', 'A1', 1, datetime('now'), datetime('now')),

-- DESTORNILLADORES
('DEST-001', 'Destornillador Plano Chico', 'Destornillador plano 3mm', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),
('DEST-002', 'Destornillador Plano Mediano', 'Destornillador plano 5mm', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),
('DEST-003', 'Destornillador Plano Grande', 'Destornillador plano 8mm', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),
('DEST-004', 'Destornillador Philips #1', 'Destornillador Philips pequeño', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),
('DEST-005', 'Destornillador Philips #2', 'Destornillador Philips mediano', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),
('DEST-006', 'Destornillador Philips #3', 'Destornillador Philips grande', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),
('DEST-007', 'Destornillador Torx T10', 'Destornillador Torx T10', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Facom', 'B1', 1, datetime('now'), datetime('now')),
('DEST-008', 'Destornillador Torx T15', 'Destornillador Torx T15', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Facom', 'B1', 1, datetime('now'), datetime('now')),
('DEST-009', 'Destornillador Torx T20', 'Destornillador Torx T20', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Facom', 'B1', 1, datetime('now'), datetime('now')),
('DEST-010', 'Juego de Destornilladores de Precisión', 'Set de 6 destornilladores de precisión', (SELECT id FROM categories WHERE name = 'Destornilladores'), 'Stanley', 'B1', 1, datetime('now'), datetime('now')),

-- ALICATES Y PINZAS
('ALIC-001', 'Alicate Universal 6"', 'Alicate universal 6 pulgadas', (SELECT id FROM categories WHERE name = 'Alicates'), 'Facom', 'C1', 1, datetime('now'), datetime('now')),
('ALIC-002', 'Alicate Universal 8"', 'Alicate universal 8 pulgadas', (SELECT id FROM categories WHERE name = 'Alicates'), 'Facom', 'C1', 1, datetime('now'), datetime('now')),
('ALIC-003', 'Alicate de Punta', 'Alicate de punta fina', (SELECT id FROM categories WHERE name = 'Alicates'), 'Stanley', 'C1', 1, datetime('now'), datetime('now')),
('ALIC-004', 'Alicate de Corte', 'Alicate de corte diagonal', (SELECT id FROM categories WHERE name = 'Alicates'), 'Stanley', 'C1', 1, datetime('now'), datetime('now')),
('ALIC-005', 'Alicate de Presión', 'Alicate de presión para tubos', (SELECT id FROM categories WHERE name = 'Alicates'), 'Facom', 'C1', 1, datetime('now'), datetime('now')),
('ALIC-006', 'Alicate Electricista', 'Alicate electricista con aislamiento', (SELECT id FROM categories WHERE name = 'Alicates'), 'Klein', 'C1', 1, datetime('now'), datetime('now')),
('PINZ-001', 'Pinza Mecánica', 'Pinza mecánica universal', (SELECT id FROM categories WHERE name = 'Alicates'), 'Facom', 'C1', 1, datetime('now'), datetime('now')),
('PINZ-002', 'Pinza de Punta Fina', 'Pinza de punta fina electrónica', (SELECT id FROM categories WHERE name = 'Alicates'), 'Stanley', 'C1', 1, datetime('now'), datetime('now')),
('PINZ-003', 'Pinza Curva', 'Pinza curva para mecánica', (SELECT id FROM categories WHERE name = 'Alicates'), 'Facom', 'C1', 1, datetime('now'), datetime('now')),

-- LLAVES
('LLAV-001', 'Llave Inglesa 8"', 'Llave inglesa 8 pulgadas', (SELECT id FROM categories WHERE name = 'Llaves'), 'Stanley', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-002', 'Llave Inglesa 10"', 'Llave inglesa 10 pulgadas', (SELECT id FROM categories WHERE name = 'Llaves'), 'Stanley', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-003', 'Llave Inglesa 12"', 'Llave inglesa 12 pulgadas', (SELECT id FROM categories WHERE name = 'Llaves'), 'Stanley', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-004', 'Juego de Llaves Fijas', 'Set de llaves fijas métricas 8-22mm', (SELECT id FROM categories WHERE name = 'Llaves'), 'Facom', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-005', 'Juego de Llaves Combinadas', 'Set de llaves combinadas métricas 8-22mm', (SELECT id FROM categories WHERE name = 'Llaves'), 'Facom', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-006', 'Juego de Llaves Allen', 'Set de llaves allen métricas', (SELECT id FROM categories WHERE name = 'Llaves'), 'Stanley', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-007', 'Juego de Llaves Torx', 'Set de llaves torx', (SELECT id FROM categories WHERE name = 'Llaves'), 'Facom', 'D1', 1, datetime('now'), datetime('now')),
('LLAV-008', 'Juego de Llaves de Tubo', 'Set de llaves de tubo', (SELECT id FROM categories WHERE name = 'Llaves'), 'Stanley', 'D1', 1, datetime('now'), datetime('now')),

-- SERRUCHOS Y SIERRAS
('SERR-001', 'Serrucho de Costilla', 'Serrucho de costilla 12"', (SELECT id FROM categories WHERE name = 'Serruchos y Sierras'), 'Stanley', 'E1', 1, datetime('now'), datetime('now')),
('SERR-002', 'Serrucho de Punta', 'Serrucho de punta fina', (SELECT id FROM categories WHERE name = 'Serruchos y Sierras'), 'Stanley', 'E1', 1, datetime('now'), datetime('now')),
('SERR-003', 'Serrucho de Arco', 'Serrucho de arco para metal', (SELECT id FROM categories WHERE name = 'Serruchos y Sierras'), 'Bosch', 'E1', 1, datetime('now'), datetime('now')),
('SIER-001', 'Sierra Caladora Manual', 'Sierra caladora manual', (SELECT id FROM categories WHERE name = 'Serruchos y Sierras'), 'Stanley', 'E1', 1, datetime('now'), datetime('now')),
('SIER-002', 'Sierra de Copa', 'Sierra de copa para madera', (SELECT id FROM categories WHERE name = 'Serruchos y Sierras'), 'Bosch', 'E1', 1, datetime('now'), datetime('now')),

-- HERRAMIENTAS DE CARPINTERÍA
('CARP-001', 'Cincel de Carpintero', 'Cincel de carpintero 1"', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-002', 'Formón', 'Formón de carpintero 1/2"', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-003', 'Gubia', 'Gubia para madera', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-004', 'Escofina', 'Escofina para madera', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-005', 'Cepillo de Carpintero', 'Cepillo de carpintero manual', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-006', 'Lima Plana', 'Lima plana fina', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-007', 'Lima Redonda', 'Lima redonda fina', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-008', 'Lima Triangular', 'Lima triangular fina', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),
('CARP-009', 'Lima Media Caña', 'Lima media caña', (SELECT id FROM categories WHERE name = 'Herramientas de Carpintería'), 'Stanley', 'F1', 1, datetime('now'), datetime('now')),

-- HERRAMIENTAS DE CORTE
('CORTE-001', 'Tijera de Chapa', 'Tijera para chapa metálica', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-002', 'Tijera de Podar', 'Tijera de podar jardín', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Fiskars', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-003', 'Tijera de Aviación', 'Tijera de aviación multipropósito', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-004', 'Tenaza', 'Tenaza universal', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Facom', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-005', 'Destornillador de Impacto', 'Destornillador de impacto manual', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Facom', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-006', 'Maceta', 'Maceta de albañil', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-007', 'Maza', 'Maza de goma', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-008', 'Puntas', 'Puntas para marcar', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-009', 'Granete', 'Granete para metal', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-010', 'Remachadora Manual', 'Remachadora manual', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-011', 'Cortafierros', 'Cortafierros chicos', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-012', 'Extractor', 'Extractor de roscas', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Facom', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-013', 'Prensa Manual', 'Prensa manual de banco', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-014', 'Sargento', 'Sargento para medición', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),
('CORTE-015', 'Gato Hidráulico', 'Gato hidráulico 2 toneladas', (SELECT id FROM categories WHERE name = 'Herramientas de Corte'), 'Stanley', 'G1', 1, datetime('now'), datetime('now')),

-- ============ ACCESORIOS ELÉCTRICOS - MECHAS Y BROCAS ============
('MEC-001', 'Set Mechas para Metal 13pzs', 'Set de mechas para metal', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-002', 'Set Mechas para Madera 8pzs', 'Set de mechas para madera', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-003', 'Set Mechas para Concreto 5pzs', 'Set de mechas para concreto', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-004', 'Mechas Multicorte Set', 'Mechas multicorte universales', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-005', 'Mecha Copa 25mm', 'Mecha copa para madera', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-006', 'Mecha Copa 40mm', 'Mecha copa para madera', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-007', 'Mecha Copa 60mm', 'Mecha copa para madera', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-008', 'Mecha Paleta 16mm', 'Mecha paleta para madera', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-009', 'Mecha Paleta 20mm', 'Mecha paleta para madera', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-010', 'Brocas SDS Plus Set', 'Set de brocas SDS Plus', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),
('MEC-011', 'Corona Perforadora 68mm', 'Corona perforadora para mampostería', (SELECT id FROM categories WHERE name = 'Mechas y Brocas'), 'Bosch', 'J1', 1, datetime('now'), datetime('now')),

-- ============ DISCOS Y HOJAS ============
('DIS-001', 'Disco Corte Metal 4½"', 'Disco de corte para metal', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Norton', 'J2', 1, datetime('now'), datetime('now')),
('DIS-002', 'Disco Corte Metal 7"', 'Disco de corte para metal', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Norton', 'J2', 1, datetime('now'), datetime('now')),
('DIS-003', 'Disco Corte Metal 9"', 'Disco de corte para metal', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Norton', 'J2', 1, datetime('now'), datetime('now')),
('DIS-004', 'Disco Desbaste 4½"', 'Disco de desbaste', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Norton', 'J2', 1, datetime('now'), datetime('now')),
('DIS-005', 'Disco Desbaste 7"', 'Disco de desbaste', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Norton', 'J2', 1, datetime('now'), datetime('now')),
('DIS-006', 'Disco Diamantado 4½"', 'Disco diamantado para mampostería', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Makita', 'J2', 1, datetime('now'), datetime('now')),
('DIS-007', 'Disco Diamantado 7"', 'Disco diamantado para mampostería', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Makita', 'J2', 1, datetime('now'), datetime('now')),
('DIS-008', 'Hoja Sierra Caladora Madera', 'Hojas para sierra caladora madera', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Bosch', 'J2', 1, datetime('now'), datetime('now')),
('DIS-009', 'Hoja Sierra Caladora Metal', 'Hojas para sierra caladora metal', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Bosch', 'J2', 1, datetime('now'), datetime('now')),
('DIS-010', 'Hoja Sierra Circular 7¼"', 'Hoja para sierra circular', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Bosch', 'J2', 1, datetime('now'), datetime('now')),
('DIS-011', 'Hoja Sierra Sable Madera', 'Hojas para sierra sable madera', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Bosch', 'J2', 1, datetime('now'), datetime('now')),
('DIS-012', 'Hoja Sierra Sable Metal', 'Hojas para sierra sable metal', (SELECT id FROM categories WHERE name = 'Discos y Hojas'), 'Bosch', 'J2', 1, datetime('now'), datetime('now')),

-- ============ LIJAS Y ABRASIVOS ============
('LIJ-101', 'Lijas Orbital Grano 80', 'Lijas para lijadora orbital', (SELECT id FROM categories WHERE name = 'Lijas y Abrasivos'), '3M', 'J3', 1, datetime('now'), datetime('now')),
('LIJ-102', 'Lijas Orbital Grano 120', 'Lijas para lijadora orbital', (SELECT id FROM categories WHERE name = 'Lijas y Abrasivos'), '3M', 'J3', 1, datetime('now'), datetime('now')),
('LIJ-103', 'Lijas Orbital Grano 180', 'Lijas para lijadora orbital', (SELECT id FROM categories WHERE name = 'Lijas y Abrasivos'), '3M', 'J3', 1, datetime('now'), datetime('now')),
('LIJ-104', 'Lijas Orbital Grano 240', 'Lijas para lijadora orbital', (SELECT id FROM categories WHERE name = 'Lijas y Abrasivos'), '3M', 'J3', 1, datetime('now'), datetime('now')),
('LIJ-105', 'Lija Banda 75x533 Grano 80', 'Lija para lijadora de banda', (SELECT id FROM categories WHERE name = 'Lijas y Abrasivos'), '3M', 'J3', 1, datetime('now'), datetime('now')),
('LIJ-106', 'Lija Banda 75x533 Grano 120', 'Lija para lijadora de banda', (SELECT id FROM categories WHERE name = 'Lijas y Abrasivos'), '3M', 'J3', 1, datetime('now'), datetime('now')),

-- ============ PUNTAS Y ADAPTADORES ============
('PUN-001', 'Set Puntas Destornillador 32pzs', 'Set de puntas para atornillador', (SELECT id FROM categories WHERE name = 'Puntas y Adaptadores'), 'Bosch', 'J4', 1, datetime('now'), datetime('now')),
('PUN-002', 'Puntas Philips PH2 x10', 'Puntas Philips', (SELECT id FROM categories WHERE name = 'Puntas y Adaptadores'), 'Bosch', 'J4', 1, datetime('now'), datetime('now')),
('PUN-003', 'Puntas Planas x10', 'Puntas planas', (SELECT id FROM categories WHERE name = 'Puntas y Adaptadores'), 'Bosch', 'J4', 1, datetime('now'), datetime('now')),
('PUN-004', 'Puntas Torx Set', 'Set de puntas Torx', (SELECT id FROM categories WHERE name = 'Puntas y Adaptadores'), 'Bosch', 'J4', 1, datetime('now'), datetime('now')),
('PUN-005', 'Adaptador Mandril', 'Adaptador para mandril', (SELECT id FROM categories WHERE name = 'Puntas y Adaptadores'), 'Bosch', 'J4', 1, datetime('now'), datetime('now')),

-- ============ MATERIALES DE CONSTRUCCIÓN - MATERIALES SECOS ============
('MAT-001', 'Cemento Portland 50kg', 'Cemento Portland bolsa 50kg', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Loma Negra', 'K1', 1, datetime('now'), datetime('now')),
('MAT-002', 'Cemento Portland 25kg', 'Cemento Portland bolsa 25kg', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Loma Negra', 'K1', 1, datetime('now'), datetime('now')),
('MAT-003', 'Cal Hidratada 25kg', 'Cal hidratada bolsa 25kg', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Calcit', 'K1', 1, datetime('now'), datetime('now')),
('MAT-004', 'Yeso Común 25kg', 'Yeso común para construcción', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Yemaco', 'K1', 1, datetime('now'), datetime('now')),
('MAT-005', 'Yeso Proyectable 30kg', 'Yeso proyectable', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Yemaco', 'K1', 1, datetime('now'), datetime('now')),
('MAT-006', 'Yeso Fino 25kg', 'Yeso fino para terminaciones', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Yemaco', 'K1', 1, datetime('now'), datetime('now')),
('MAT-007', 'Mortero Premezclado 30kg', 'Mortero premezclado', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Weber', 'K1', 1, datetime('now'), datetime('now')),
('MAT-008', 'Enduido Interior 25kg', 'Enduido para interior', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Revear', 'K1', 1, datetime('now'), datetime('now')),
('MAT-009', 'Enduido Exterior 25kg', 'Enduido para exterior', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Revear', 'K1', 1, datetime('now'), datetime('now')),
('MAT-010', 'Adhesivo Cerámico 30kg', 'Adhesivo para cerámicos', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Klaukol', 'K1', 1, datetime('now'), datetime('now')),
('MAT-011', 'Pastina Blanca 2kg', 'Pastina para cerámicos', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Klaukol', 'K1', 1, datetime('now'), datetime('now')),
('MAT-012', 'Membrana en Pasta 20kg', 'Membrana impermeabilizante', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'Sika', 'K1', 1, datetime('now'), datetime('now')),
('MAT-013', 'Arena Fina 25kg', 'Arena fina bolsa', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'General', 'K1', 1, datetime('now'), datetime('now')),
('MAT-014', 'Cascote 25kg', 'Cascote bolsa', (SELECT id FROM categories WHERE name = 'Materiales Secos'), 'General', 'K1', 1, datetime('now'), datetime('now')),

-- ============ MAMPOSTERÍA ============
('MAM-001', 'Ladrillo Común', 'Ladrillo común de construcción', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-002', 'Ladrillo Hueco 8cm', 'Ladrillo hueco 8cm', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-003', 'Ladrillo Hueco 12cm', 'Ladrillo hueco 12cm', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-004', 'Ladrillo Hueco 18cm', 'Ladrillo hueco 18cm', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-005', 'Ladrillo Portante', 'Ladrillo portante para estructura', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-006', 'Ladrillo Refractario', 'Ladrillo refractario', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-007', 'Ladrillo Visto', 'Ladrillo a la vista', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Ladrillera', 'K2', 1, datetime('now'), datetime('now')),
('MAM-008', 'Bloque Hormigón 10cm', 'Bloque de hormigón 10cm', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Bloques SA', 'K2', 1, datetime('now'), datetime('now')),
('MAM-009', 'Bloque Hormigón 15cm', 'Bloque de hormigón 15cm', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Bloques SA', 'K2', 1, datetime('now'), datetime('now')),
('MAM-010', 'Bloque Hormigón 20cm', 'Bloque de hormigón 20cm', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Bloques SA', 'K2', 1, datetime('now'), datetime('now')),
('MAM-011', 'Chapa Acanalada 3.05m', 'Chapa galvanizada acanalada', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Siderar', 'K2', 1, datetime('now'), datetime('now')),
('MAM-012', 'Chapa Trapezoidal 3.05m', 'Chapa trapezoidal', (SELECT id FROM categories WHERE name = 'Mampostería'), 'Siderar', 'K2', 1, datetime('now'), datetime('now')),

-- ============ HIERROS Y METALES ============
('HIE-001', 'Varilla 6mm x 12m', 'Varilla de construcción 6mm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-002', 'Varilla 8mm x 12m', 'Varilla de construcción 8mm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-003', 'Varilla 10mm x 12m', 'Varilla de construcción 10mm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-004', 'Varilla 12mm x 12m', 'Varilla de construcción 12mm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-005', 'Alambre Negro kg', 'Alambre negro por kg', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-006', 'Alambre Galvanizado kg', 'Alambre galvanizado por kg', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-007', 'Malla Electrosoldada 15x15', 'Malla electrosoldada 15x15cm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Acindar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-008', 'Ángulo de Hierro 25x25', 'Ángulo de hierro 25x25mm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Siderar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-009', 'Caño Estructural 40x40', 'Caño estructural cuadrado', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Siderar', 'K3', 1, datetime('now'), datetime('now')),
('HIE-010', 'Chapa Lisa 1mm', 'Chapa lisa espesor 1mm', (SELECT id FROM categories WHERE name = 'Hierros y Metales'), 'Siderar', 'K3', 1, datetime('now'), datetime('now')),

-- ============ MADERAS Y DERIVADOS ============
('MAD-001', 'Tabla de Pino 1x6x3m', 'Tabla de pino cepillada', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Maderera', 'K4', 1, datetime('now'), datetime('now')),
('MAD-002', 'Tirante 2x4x3m', 'Tirante de pino', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Maderera', 'K4', 1, datetime('now'), datetime('now')),
('MAD-003', 'Listón 2x2x3m', 'Listón de pino', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Maderera', 'K4', 1, datetime('now'), datetime('now')),
('MAD-004', 'Machimbre Pino 10cm', 'Machimbre de pino', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Maderera', 'K4', 1, datetime('now'), datetime('now')),
('MAD-005', 'Fenólico 18mm 2.44x1.22', 'Placa fenólica', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Masisa', 'K4', 1, datetime('now'), datetime('now')),
('MAD-006', 'MDF 18mm 2.75x1.83', 'Placa MDF', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Masisa', 'K4', 1, datetime('now'), datetime('now')),
('MAD-007', 'Aglomerado 18mm', 'Placa de aglomerado', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Masisa', 'K4', 1, datetime('now'), datetime('now')),
('MAD-008', 'Terciado 5mm', 'Terciado fino', (SELECT id FROM categories WHERE name = 'Maderas y Derivados'), 'Masisa', 'K4', 1, datetime('now'), datetime('now')),

-- ============ PINTURAS ============
('PIN-001', 'Látex Interior Blanco 20L', 'Látex para interiores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-002', 'Látex Interior Blanco 10L', 'Látex para interiores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-003', 'Látex Interior Blanco 4L', 'Látex para interiores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-004', 'Látex Exterior Blanco 20L', 'Látex para exteriores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sherwin Williams', 'L1', 1, datetime('now'), datetime('now')),
('PIN-005', 'Látex Exterior Blanco 10L', 'Látex para exteriores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sherwin Williams', 'L1', 1, datetime('now'), datetime('now')),
('PIN-006', 'Látex Lavable Blanco 20L', 'Látex lavable premium', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sherwin Williams', 'L1', 1, datetime('now'), datetime('now')),
('PIN-007', 'Esmalte Sintético Blanco 4L', 'Esmalte sintético brillante', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-008', 'Esmalte Sintético Negro 4L', 'Esmalte sintético brillante', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-009', 'Antióxido Rojo 4L', 'Antióxido convertidor', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sinteplast', 'L1', 1, datetime('now'), datetime('now')),
('PIN-010', 'Antióxido Gris 4L', 'Antióxido convertidor', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sinteplast', 'L1', 1, datetime('now'), datetime('now')),
('PIN-011', 'Fondo para Madera 4L', 'Fondo sellador para madera', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-012', 'Fondo para Paredes 20L', 'Fondo fijador para paredes', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-013', 'Barniz Marino 4L', 'Barniz marino para exteriores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Cetol', 'L1', 1, datetime('now'), datetime('now')),
('PIN-014', 'Barniz Común 4L', 'Barniz para interiores', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Alba', 'L1', 1, datetime('now'), datetime('now')),
('PIN-015', 'Impermeabilizante Acrílico 20L', 'Impermeabilizante para techos', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sika', 'L1', 1, datetime('now'), datetime('now')),
('PIN-016', 'Membrana Líquida 20kg', 'Membrana líquida impermeabilizante', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Igol', 'L1', 1, datetime('now'), datetime('now')),
('PIN-017', 'Pintura para Pisos Gris 4L', 'Pintura epoxi para pisos', (SELECT id FROM categories WHERE name = 'Pinturas'), 'Sinteplast', 'L1', 1, datetime('now'), datetime('now'));
